# Generated by Django 4.0.2 on 2022-02-14 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(max_length=100, verbose_name='Nom du categorie')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100, verbose_name='model')),
                ('date_created', models.DateTimeField(null=True, verbose_name="Date de l'ajout")),
                ('image', models.ImageField(upload_to='image/% Y/% m/% d/', verbose_name="Ajouter l'image")),
                ('status', models.CharField(choices=[('OK', 'OK'), ('Défectué', 'Défectué')], max_length=200, null=True, verbose_name='statut')),
                ('info', models.CharField(max_length=500, verbose_name='Info')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.categorie')),
            ],
        ),
    ]
